Header header

# 左转向灯状态  true: 开, false: 关
bool left_light
# 右转向灯状态  true: 开, false: 关
bool right_light

# 远光灯状态  true: 开, false: 关
bool high_light
# 近光灯状态  true: 开, false: 关
bool low_light

# 刹车灯状态  true: 开, false: 关
bool brake_light
# 危险报警灯状态  true: 开, false: 关
bool emergency_light
# 雾灯状态  true: 开, false: 关
bool front_foggy_light
bool rear_foggy_light
bool position_light
bool reverse_light

# 喇叭  true: 开, false: 关
bool horn

bool wiper
bool head_light