<?xml version="1.0"?>
<package format="2">
  <name>task_scheduler</name>
  <version>0.0.0</version>
  <description>UGV multi-vehicle task scheduler based on the global road network map.</description>
  <maintainer email="zhaozhe@todo.todo">zhaozhe</maintainer>
  <license>TODO</license>

  <buildtool_depend>catkin</buildtool_depend>

  <build_depend>geometry_msgs</build_depend>
  <build_depend>roscpp</build_depend>
  <build_depend>roslib</build_depend>
  <build_depend>route_msgs</build_depend>
  <build_depend>std_msgs</build_depend>
  <build_depend>tf</build_depend>
  <build_depend>utm</build_depend>
  <build_depend>visualization_msgs</build_depend>
  <build_depend>pugixml</build_depend>

  <exec_depend>geometry_msgs</exec_depend>
  <exec_depend>roscpp</exec_depend>
  <exec_depend>roslib</exec_depend>
  <exec_depend>route_msgs</exec_depend>
  <exec_depend>std_msgs</exec_depend>
  <exec_depend>tf</exec_depend>
  <exec_depend>utm</exec_depend>
  <exec_depend>visualization_msgs</exec_depend>
  <exec_depend>pugixml</exec_depend>

  <export>
  </export>
</package>
