######################################################################
# Automatically generated by qmake (3.1) Mon Sep 19 15:17:29 2022
######################################################################

TEMPLATE = app
TARGET = pad
INCLUDEPATH += .
QT += core gui network widgets
# The following define makes your compiler warn you if you use any
# feature of Qt which has been marked as deprecated (the exact warnings
# depend on your compiler). Please consult the documentation of the
# deprecated API in order to know how to port your code away from it.
DEFINES += QT_DEPRECATED_WARNINGS

# You can also make your code fail to compile if you use deprecated APIs.
# In order to do so, uncomment the following line.
# You can also select to disable deprecated APIs only up to a certain version of Qt.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0

# Input

SUBDIRS += \
    pad.pro

RESOURCES += \
    resource/images.qrc

FORMS += \
    ui/chassislighthornwiperdlg.ui \
    ui/configdialog.ui \
    ui/mapfilegeneration.ui \
    ui/parentdlg.ui \
    ui/PosMeasureDlg.ui \
    ui/platoondlg.ui \
    ui/vehiclewirecontrol.ui \
    ui/updatefile.ui

DISTFILES += \
    resource/images/foxy.jpg \
    resource/images/ros-icon.png

INCLUDEPATH +=./include/ \
/usr/include/pcl-1.8/ \
/opt/ros/melodic/include \
/home/zwy/catinros/devel/include


HEADERS += \
    include/pad/alldeclare.h \
    include/pad/allglobal.h \
    include/pad/allheader.h \
    include/pad/allmacro.h \
    include/pad/alltypes.h \
    include/pad/astar.h \
    include/pad/chassislighthornwiperdialog.h \
    include/pad/configdialog.h \
    include/pad/llh2enu.h \
    include/pad/mapfilegeneration.h \
    include/pad/netrecv.h \
    include/pad/netsend.h \
    include/pad/parentdlg.h \
    include/pad/PosMeasureDlg.h \
    include/pad/rclcomm.h \
    include/pad/record.h \
    include/pad/qnode.h \ \
    include/pad/vehiclewirecontrol.h \
    include/pad/platoondlg.h \
    include/pad/updatefile.h


SOURCES += \
    src/astar.cpp \
    src/chassislighthornwiperdialog.cpp \
    src/configdialog.cpp \
    src/llh2enu.cpp \
    src/main.cpp \
    src/mapfilegeneration.cpp \
    src/netrecv.cpp \
    src/netsend.cpp \
    src/parentdlg.cpp \
    src/PosMeasureDlg.cpp \
    src/rclcomm.cpp \
    src/record.cpp \
    src/qnode.cpp \
    src/vehiclewirecontrol.cpp \
    src/platoondlg.cpp \
    src/updatefile.cpp

