<?xml version="1.0"?>
<package format="2">
  <name>calibrate_steer</name>
  <version>0.0.0</version>
  <description>The calibrate_steer package</description>
  <maintainer email="robotpengxu@gmail.com">Peng Xu</maintainer>
  <license>MIT</license>
  <buildtool_depend>catkin</buildtool_depend>
  <build_depend>roslint</build_depend>
  <build_depend>rospy</build_depend>
  <build_depend>utm</build_depend>
  <build_depend>yaml-cpp</build_depend>
  <build_depend>eigen3</build_depend>
  <build_depend>roslib</build_depend>
  <export>
  </export>
</package>
