<?xml version="1.0"?>
<package format="2">
  <name>simulate</name>
  <version>0.0.0</version>
  <description>The simulate package</description>
  <maintainer email="robotpengxu@gmail.com">Peng Xu</maintainer>
  <license>MIT</license>
  <buildtool_depend>catkin</buildtool_depend>
  <build_depend>rospy</build_depend> 
  <build_depend>roslib</build_depend> 
  <build_depend>planning_msg</build_depend>
  <build_depend>driver_msgs</build_depend>
  <build_depend>autoware_msgs</build_depend>
  <build_depend>ins_msgs</build_depend>
  <build_depend>localization_msgs</build_depend>
  <build_depend>tf</build_depend>
  <build_depend>nav_msgs</build_depend>
  <build_depend>visualization_msgs</build_depend>
  <build_export_depend>rospy</build_export_depend>
  <exec_depend>rospy</exec_depend>
  <exec_depend>nav_msgs</exec_depend>
  <exec_depend>tf</exec_depend>
  <exec_depend>visualization_msgs</exec_depend>
  <build_depend>amathutils_lib</build_depend>
  <build_depend>vehicle_info_util</build_depend>  
  <build_depend>utm</build_depend> 
  <build_depend>ray_msgs</build_depend>  
  <build_depend>platoon_common</build_depend>
  <build_depend>common</build_depend>   
  <build_depend>route_msgs</build_depend> 


  <export>
  </export>
</package>
