weight_fem_pos_deviation: 1.0e10 
weight_ref_deviation: 1.0
weight_path_length: 1.0
apply_curvature_constraint: true
weight_curvature_constraint_slack_var: 1.0e2
curvature_constraint: 0.2
use_sqp: false
sqp_ftol: 1e-4
sqp_ctol: 1e-3
sqp_pen_max_iter: 10
sqp_sub_max_iter: 100
max_iter: 500
time_limit: 0.0
verbose: false
scaled_termination: true
warm_start: true
print_level: 0
max_num_of_iterations: 500
acceptable_num_of_iterations: 15
tol: 1e-8
acceptable_tol: 1e-1
lat_bound: 1.0
