<?xml version="1.0"?>
<package format="2">
  <name>velocity_planner</name>
  <version>1.12.0</version>
  <description>The libamathutils package</description>
  <maintainer email="yusuke.fujii@tier4.jp">Yusuke FUJII</maintainer>
  <author email="yusuke.fujii@tier4.jp">Yusuke FUJII</author>
  <license>Apache 2</license>
  <buildtool_depend>catkin</buildtool_depend>
  <build_depend>vehicle_info_util</build_depend>
  <build_depend>platoon_common</build_depend> 
  <build_depend>platoon_msgs</build_depend>
  <build_depend>planner_msgs</build_depend>
  <build_depend>common</build_depend>
  <depend>roscpp</depend>
  <depend>amathutils_lib</depend>
  <depend>roslint</depend>
  <depend>driver_msgs</depend>
  <depend>perception_msgs</depend>
  <depend>planning_msgs</depend>
  <depend>std_msgs</depend>
  <depend>roslib</depend>

</package>
